# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='quantity',
            new_name='price',
        ),
    ]
