# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0007_auto_20190518_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upvoter',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
