# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190526_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='To do', max_length=20),
        ),
    ]
