# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190514_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureupvote',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='featureupvote',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
        migrations.AlterField(
            model_name='featureupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_upvoter', to=settings.AUTH_USER_MODEL),
        ),
    ]
