# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190514_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecomment',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
    ]
