# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20190514_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
