# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_feature_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureupvote',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
