# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20190514_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureupvote',
            old_name='amount_paid',
            new_name='fee',
        ),
    ]
