# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_feature_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
