# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20190515_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureupvote',
            name='fee',
        ),
        migrations.AddField(
            model_name='feature',
            name='upvote_fee',
            field=models.IntegerField(default=5),
        ),
    ]
