# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_auto_20190515_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='upvote_fee',
            new_name='price',
        ),
    ]
