# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_auto_20190515_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
