# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_auto_20190516_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='price',
        ),
    ]
