# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
