# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='date_submitted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
