# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190412_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
