# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_bugupvote_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='status',
        ),
        migrations.AddField(
            model_name='bug',
            name='year_in_school',
            field=models.CharField(choices=[('TD', 'To do'), ('IP', 'In progress'), ('DN', 'Done')], default='TD', max_length=2),
        ),
    ]
