# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190514_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BugComment',
        ),
        migrations.RenameModel(
            old_name='Upvote',
            new_name='BugUpvote',
        ),
    ]
