# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190430_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='submitter',
            new_name='author',
        ),
    ]
