# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20190430_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='author',
            new_name='submitter',
        ),
    ]
