# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20190526_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='year_in_school',
            new_name='status',
        ),
    ]
