# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_auto_20190514_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomment',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.Bug'),
        ),
        migrations.AlterField(
            model_name='bugupvote',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.Bug'),
        ),
        migrations.AlterField(
            model_name='bugupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
