# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20190430_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='upvoters',
            field=models.TextField(null=True),
        ),
    ]
