# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0009_auto_20190502_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='upvoters',
        ),
    ]
